<html>
  <body>
    <p>お問い合わせがありました。<br></p>
    <p>【お問い合わせ内容】</p>
    <p>お名前：{{$contact['name']}}</p>
    <p>メールアドレス：{{$contact['email']}}</p>
    <p>お問い合わせ内容：{{$contact['content']}}</p>
  </body>
</html>